# -*- coding: utf-8 -*-
from .temporary_metrics import *

# Legacy Device Meta Definitions
ALL = {
    META_AIR_BAROMETRIC_PRESSURE: {
        "groups": ["~environment"],
        "json_schema": {"type": "number"},
        "unit_of_measure": "Pa",
        "value": 0,
    },
    META_AIR_CO2: {
        "groups": ["~environment"],
        "json_schema": {"type": "number"},
        "unit_of_measure": "ppm",
        "value": 0,
    },
    META_AIR_VOC: {"groups": ["~environment"], "json_schema": {"type": "number"}, "value": 0},
    META_AMBIENT_NOISE: {
        "groups": ["~environment"],
        "json_schema": {"type": "number"},
        "unit_of_measure": "dB",
        "value": 0,
    },
    META_AMBIENT_TEMPERATURE: {
        "groups": ["~environment", "~rule_trigger"],
        "json_schema": {"type": "number"},
        "unit_of_measure": "C",
        "value": 0,
        "value_display_name": {
            "type": "range",
            "range:-100-0": "Freezing",
            "range:100-1000": "Boiling",
        },
    },
    META_CO2_SETPOINT: {
        "value": 0,
        "display_name": "CO2 Setpoint",
        "unit_of_measure": "ppm",
        "json_schema": {"type": "number"},
        "groups": ["ctrl_co2"],
    },
    META_COOLING_VALVE: {
        "value": 0,
        "display_name": "Cooling Valve",
        "groups": ["~environment"],
        "unit_of_measure": "%",
        "json_schema": {"type": "number"},
    },
    META_ENABLE: {
        "value": "",
        "display_name": "Enable",
        "json_schema": {"type": "boolean"},
        "value_display_name": {"type": "enum", "true": "Enable", "false": "Disable"},
        "groups": ["ctrl_enable"],
    },
    META_EXTRACT_FAN_PRESSURE_SETPOINT: {
        "value": 0,
        "display_name": "Extract Fan Pressure Setpoint",
        "unit_of_measure": "Pa",
        "json_schema": {"type": "number"},
        "groups": ["ctrl_extract_pressure"],
    },
    META_EXTRACTFAN_SPEED_SETPOINT: {
        "value": 0,
        "display_name": "Extract Fan Speed Setpoint",
        "unit_of_measure": "%",
        "groups": ["ctrl_extract_fan_speed"],
        "json_schema": {"type": "number", "minimum": 0, "maximum": 100},
        "value_display_name": {
            "type": "range",
            "range:0": "Off",
            "range:1-33": "Low",
            "range:34-66": "Medium",
            "range:67-100": "High",
        },
    },
    META_EXTRACT_TEMPERATURE_SETPOINT: {
        "value": 0,
        "display_name": "Extract Temperature Setpoint",
        "unit_of_measure": "C",
        "json_schema": {"type": "number"},
        "groups": ["ctrl_extract_temperature"],
        "value_display_name": {
            "type": "range",
            "range:-100-0": "Freezing",
            "range:100-1000": "Boiling",
        },
    },
    META_FAN_MODE: {
        "value": "",
        "display_name": "Fan Mode",
        "json_schema": {"type": "string", "enum": ["", "Low", "Medium", "High"]},
        "groups": ["ctrl_fan_mode"],
    },
    META_FLOW_PRESSURE_SETPOINT: {
        "value": 0,
        "display_name": "Pressure Setpoint",
        "unit_of_measure": "Pa",
        "json_schema": {"type": "number"},
        "groups": ["ctrl_flow_pressure"],
    },
    META_FLOW_TEMPERATURE_SET_POINT: {
        "value": 0,
        "display_name": "Flow Temperature Setpoint",
        "unit_of_measure": "C",
        "json_schema": {"type": "number"},
        "groups": ["ctrl_flow_temperature"],
        "value_display_name": {
            "type": "range",
            "range:-100-0": "Freezing",
            "range:100-1000": "Boiling",
        },
    },
    META_HEAT_PUMP_MODE: {
        "value": "",
        "display_name": "Mode",
        "json_schema": {"type": "string", "enum": ["", "Heating", "Cooling"]},
        "groups": ["ctrl_mode"],
    },
    META_HEATING_VALVE: {
        "value": 0,
        "display_name": "Heating Valve",
        "groups": ["~environment"],
        "unit_of_measure": "%",
        "json_schema": {"type": "number"},
    },
    META_HUMIDITY_SETPOINT: {
        "value": 0,
        "display_name": "Humidity Setpoint",
        "unit_of_measure": "%RH",
        "json_schema": {"type": "number"},
        "groups": ["ctrl_humidity"],
    },
    META_LOUVERS: {
        "display_name": "Louvers",
        "groups": ["ctrl_louvers"],
        "json_schema": {"type": "boolean"},
        "value": "",
        "value_display_name": {"type": "enum", "true": "Swing", "false": "Fixed"},
    },
    META_MODE: {
        "value": "",
        "display_name": "Mode",
        "json_schema": {"type": "string", "enum": ["", "Heat", "Cool", "Air", "Auto"]},
        "groups": ["ctrl_mode"],
    },
    META_RETURN_SETPOINT: {
        "value": 0,
        "display_name": "Return Setpoint",
        "unit_of_measure": "C",
        "json_schema": {"type": "number"},
        "groups": ["ctrl_return_temperature"],
        "value_display_name": {
            "type": "range",
            "range:-100-0": "Freezing",
            "range:100-1000": "Boiling",
        },
    },
    META_SPEED_SETPOINT: {
        "value": 0,
        "display_name": "Speed Setpoint",
        "unit_of_measure": "%",
        "groups": ["ctrl_speed"],
        "json_schema": {"type": "number", "minimum": 0, "maximum": 100},
        "value_display_name": {
            "type": "range",
            "range:0": "Off",
            "range:1-33": "Low",
            "range:34-66": "Medium",
            "range:67-100": "High",
        },
    },
    META_SUPPLY_FAN_PRESSURE_SETPOINT: {
        "value": 0,
        "display_name": "Supply Fan Pressure Setpoint",
        "unit_of_measure": "Pa",
        "json_schema": {"type": "number"},
        "groups": ["ctrl_supply_pressure"],
    },
    META_SUPPLY_TEMPERATURE_SETPOINT: {
        "value": 0,
        "display_name": "Supply Temperature Setpoint",
        "unit_of_measure": "C",
        "json_schema": {"type": "number"},
        "value_display_name": {
            "type": "range",
            "range:-100-0": "Freezing",
            "range:100-1000": "Boiling",
        },
        "groups": ["ctrl_supply_temperature"],
    },
    META_X1_SETPOINT: {
        "value": 0,
        "display_name": "X1 Setpoint",
        "unit_of_measure": "C",
        "json_schema": {"type": "number"},
        "groups": ["ctrl_x1"],
        "value_display_name": {
            "type": "range",
            "range:-100-0": "Freezing",
            "range:100-1000": "Boiling",
        },
    },
    META_X2_SETPOINT: {
        "value": 0,
        "display_name": "X2 Setpoint",
        "unit_of_measure": "C",
        "json_schema": {"type": "number"},
        "groups": ["ctrl_x2"],
        "value_display_name": {
            "type": "range",
            "range:-100-0": "Freezing",
            "range:100-1000": "Boiling",
        },
    },
    META_Y1_SETPOINT: {
        "value": 0,
        "display_name": "Y1 Setpoint",
        "unit_of_measure": "C",
        "json_schema": {"type": "number"},
        "groups": ["ctrl_y1"],
        "value_display_name": {
            "type": "range",
            "range:-100-0": "Freezing",
            "range:100-1000": "Boiling",
        },
    },
    META_Y2_SETPOINT: {
        "value": 0,
        "display_name": "Y2 Setpoint",
        "unit_of_measure": "C",
        "json_schema": {"type": "number"},
        "groups": ["ctrl_y2"],
        "value_display_name": {
            "type": "range",
            "range:-100-0": "Freezing",
            "range:100-1000": "Boiling",
        },
    },
}
